// GENERATED, DO NOT EDIT THIS FILE
package github

import (
	"github.com/cloudskiff/driftctl/pkg/resource"
	rescty "github.com/cloudskiff/driftctl/pkg/resource/cty"
	"github.com/zclconf/go-cty/cty"
)

const GithubMembershipResourceType = "github_membership"

type GithubMembership struct {
	Etag     *string    `cty:"etag" computed:"true" diff:"-"`
	Id       string     `cty:"id" computed:"true"`
	Role     *string    `cty:"role"`
	Username *string    `cty:"username"`
	CtyVal   *cty.Value `diff:"-"`
}

func (r *GithubMembership) TerraformId() string {
	return r.Id
}

func (r *GithubMembership) TerraformType() string {
	return GithubMembershipResourceType
}

func (r *GithubMembership) CtyValue() *cty.Value {
	return r.CtyVal
}

func initGithubMembershipMetadata(resourceSchemaRepository *resource.SchemaRepository) {
	resourceSchemaRepository.SetNormalizeFunc(GithubMembershipResourceType, func(val *rescty.CtyAttributes) {
		val.SafeDelete([]string{"etag"})
	})
}
