package github

import "github.com/cloudskiff/driftctl/pkg/resource"

func InitMetadatas(resourceSchemaRepository resource.SchemaRepositoryInterface) {
	initGithubBranchProtectionMetadata(resourceSchemaRepository)
	initGithubTeamMembershipMetadata(resourceSchemaRepository)
	initGithubMembershipMetadata(resourceSchemaRepository)
	initGithubTeamMetadata(resourceSchemaRepository)
	initGithubRepositoryMetadata(resourceSchemaRepository)
}
