// GENERATED, DO NOT EDIT THIS FILE
package aws

import (
	"github.com/cloudskiff/driftctl/pkg/resource"
	rescty "github.com/cloudskiff/driftctl/pkg/resource/cty"
	"github.com/zclconf/go-cty/cty"
)

const AwsKmsAliasResourceType = "aws_kms_alias"

type AwsKmsAlias struct {
	Arn          *string    `cty:"arn" computed:"true"`
	Id           string     `cty:"id" computed:"true"`
	Name         *string    `cty:"name" diff:"-"`
	NamePrefix   *string    `cty:"name_prefix" diff:"-"`
	TargetKeyArn *string    `cty:"target_key_arn" computed:"true"`
	TargetKeyId  *string    `cty:"target_key_id"`
	CtyVal       *cty.Value `diff:"-"`
}

func (r *AwsKmsAlias) TerraformId() string {
	return r.Id
}

func (r *AwsKmsAlias) TerraformType() string {
	return AwsKmsAliasResourceType
}

func (r *AwsKmsAlias) CtyValue() *cty.Value {
	return r.CtyVal
}

func initAwsKmsAliasMetaData(resourceSchemaRepository *resource.SchemaRepository) {
	resourceSchemaRepository.SetNormalizeFunc(AwsKmsAliasResourceType, func(val *rescty.CtyAttributes) {
		val.SafeDelete([]string{"name"})
		val.SafeDelete([]string{"name_prefix"})
	})
}
