// GENERATED, DO NOT EDIT THIS FILE
package aws

import (
	"github.com/cloudskiff/driftctl/pkg/resource"
	rescty "github.com/cloudskiff/driftctl/pkg/resource/cty"
	"github.com/zclconf/go-cty/cty"
)

const AwsS3BucketPolicyResourceType = "aws_s3_bucket_policy"

type AwsS3BucketPolicy struct {
	Bucket *string    `cty:"bucket" diff:"-"`
	Id     string     `cty:"id" diff:"-" computed:"true"`
	Policy *string    `cty:"policy" jsonstring:"true"`
	CtyVal *cty.Value `diff:"-"`
}

func (r *AwsS3BucketPolicy) TerraformId() string {
	return r.Id
}

func (r *AwsS3BucketPolicy) TerraformType() string {
	return AwsS3BucketPolicyResourceType
}

func (r *AwsS3BucketPolicy) CtyValue() *cty.Value {
	return r.CtyVal
}

func initAwsS3BucketPolicyMetaData(resourceSchemaRepository *resource.SchemaRepository) {
	resourceSchemaRepository.SetNormalizeFunc(AwsS3BucketPolicyResourceType, func(val *rescty.CtyAttributes) {
		val.SafeDelete([]string{"bucket"})
		val.SafeDelete([]string{"id"})
	})
	resourceSchemaRepository.UpdateSchema(AwsS3BucketPolicyResourceType, map[string]func(attributeSchema *resource.AttributeSchema){
		"policy": func(attributeSchema *resource.AttributeSchema) {
			attributeSchema.JsonString = true
		},
	})
}
